// Generated by flutterfire configure. Replace this file with the real one.
// Run: flutterfire configure --project=YOUR_FIREBASE_PROJECT_ID
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace all values below with your real Firebase project credentials
  // after running: flutterfire configure --project=YOUR_FIREBASE_PROJECT_ID

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_WEB_API_KEY',
    appId: 'REPLACE_WITH_WEB_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'REPLACE_WITH_PROJECT_ID',
    authDomain: 'REPLACE_WITH_PROJECT_ID.firebaseapp.com',
    storageBucket: 'REPLACE_WITH_PROJECT_ID.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB44YWt01Vqpnu5GTCQHChAsEyBghVwRpk',
    appId: '1:893780722918:android:0bd61e4fe204177f046727',
    messagingSenderId: '893780722918',
    projectId: 'eacademia-app',
    storageBucket: 'eacademia-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBPKmuxMpLm2GG4enQiGegxnTLk2FEGv0',
    appId: '1:893780722918:ios:7dec4dde00983c94046727',
    messagingSenderId: '893780722918',
    projectId: 'eacademia-app',
    storageBucket: 'eacademia-app.firebasestorage.app',
    iosBundleId: 'com.granions.eacademia',
  );

}